version: "3.8"

services:
  gateway:
    build:
      context: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8001:8000"
    depends_on:
      - model

  model:
    build:
      context: ./model
    ports:
      - "8002:8000"